# Your name and what you do
name: Lopez Software Development
bio: Research and development for blockchain solutions.

description: Lopez Software Development Website

# Profile picture
picture: assets/images/profile.png
 
url: https://0xlopezsd.github.io

# do you want to display social media links? true or false
social-media: false
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: 0xlopezsd
# linkedin: christopher-césar-chávez-lópez-27566b12
github: 0xlopezsd
# email: 0xlopezsd@gmail.com
# cv: assets/cv-dapp._pdf
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - <b>Automation </b> OpenZepelling Defender, Gelato Network, Chainlink Keepers 
    - <b>Analytics </b> Monitoring, Dune Dashboards
    - <b>Smart contract developement </b> Solidity
    - <b>Smart contract testing </b>  Typescript, mocha, Hardhat, Ganache.
    - <b>Web3</b>  Web3.js, Ethers, Truffle, Metamask


# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    packd-contracts:
        name: PACD
        description: Packs are composable ERC721s that own accounts based on the ERC6551 standard.
        url: https://app.packd.io/
        tags: Smart Contract Development, Advisor
    mStable-contracts:
        name: mStable
        description: Decentralised Stablecoin Ecosystem
        url: https://github.com/mstable/mStable-contracts
        tags: Smart Contract Development, Research, Smart Contract Automation
    react-jsonschema-form:
        name: react-jsonschema-form
        description: A simple React component capable of building HTML forms out of a JSON schema.
        url: https://github.com/rjsf-team/react-jsonschema-form
        tags: Open source contribution    

# do you want to display a badges section? true or false
badges: false

# add your badges here
badge-list:
    Ethereum-Bootcamp-Udemy:
        name: Ethereum Blockchain Developer Bootcamp With Solidity (2021)
        organization: Udemy
        url: https://udemy-certificate.s3.amazonaws.com/image/UC-bfbb4b81-b372-4e47-9043-a155557f1a1a.jpg

# do you want to display a badges section? true or false
contributors: true

# add your badges here
contributor-list:
    doncesarts:
        name: doncesarts.eth
        organization: 0xlopezsd
        url: https://github.com/doncesarts



# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
